/** Typed access to the published artifacts.
 *
 * These files are generated by pipeline/publish.py and committed. Nothing here
 * computes a statistic — if a number needs to change, it changes upstream and
 * is regenerated. The site's job is to render what the pipeline published, and
 * to state the window that came with it.
 */

import metaJson from "@/data/generated/meta.json";
import tripsMonthlyJson from "@/data/generated/trips_monthly.json";
import seasonalityJson from "@/data/generated/seasonality.json";
import stationsYearlyJson from "@/data/generated/stations_yearly.json";
import ebikeJson from "@/data/generated/ebike_share.json";
import durationJson from "@/data/generated/duration.json";
import exclusionsJson from "@/data/generated/exclusions.json";
import incompleteJson from "@/data/generated/incomplete_months.json";
import stationsMetaJson from "@/data/generated/stations_meta.json";
// Eager, unlike stations.json. At under 2 KB gzip against that file's 68 KB,
// a second lazy path would buy little and cost a failure mode — and spec 021
// demonstrated how quietly a lazy path can fail.
import flowsJson from "@/data/generated/flows.json";
// 5 KB gzip — eager, for the same reason flows.json is.
import membershipJson from "@/data/generated/membership.json";
// 2.3 KB and 1.2 KB gzip.
import rebalancingJson from "@/data/generated/rebalancing.json";
import dwellJson from "@/data/generated/dwell.json";
import type { SystemId } from "@/lib/systems";

export interface SystemMetaRow {
  system_id: SystemId;
  city: string;
  system: string;
  trips: number;
  first_trip: string;
  last_trip: string;
  /** Distinct station IDENTITIES, not physical stations — Montreal's three
   *  unbridged key spaces inflate it. Do not render as a station count. */
  station_identities_seen: number;
  stations_note: string;
  active_stations: number;
  flagged: number;
}

export interface Meta {
  generated_at: string;
  common_window_first_year: string;
  systems: SystemMetaRow[];
  window_note: string;
}

export interface MonthPoint { system_id: SystemId; month: string; trips: number }
export interface SeasonPoint { system_id: SystemId; month_of_year: number; mean_trips: number }
export interface StationPoint { system_id: SystemId; year: number; stations: number }
export interface EbikePoint {
  system_id: SystemId;
  month: string;
  ebike_trips: number;
  classified_trips: number;
}
export interface DurationRow {
  system_id: SystemId;
  median_s: number;
  p25_s: number;
  p75_s: number;
  basis_trips: number;
}
export interface ExclusionRow {
  system_id: SystemId;
  unterminated: number;
  station_matched_by_name: number;
  total: number;
}

export const meta = metaJson as Meta;
export const tripsMonthly = tripsMonthlyJson as MonthPoint[];
export const seasonality = seasonalityJson as { first_year: number; series: SeasonPoint[] };
export const stationsYearly = stationsYearlyJson as StationPoint[];
export const ebikeShare = ebikeJson as {
  series: EbikePoint[];
  unsupported: Record<string, { reason?: string; display?: string }>;
};
export const durations = durationJson as DurationRow[];
export const exclusions = exclusionsJson as ExclusionRow[];

/** Months excluded from every series because the source has not finished
 *  publishing them (or, for van-mobi 2022-10, because the file will not
 *  download). Rendered on the site rather than buried in the runbook. */
export interface StationPin {
  /** system_id */ s: SystemId;
  /** station key */ i: string;
  /** name */ n: string;
  /** lat */ y: number;
  /** lon */ x: number;
  /** lifetime events */ t: number;
  /** currently active */ a: boolean;
  /** net flow: returns minus departures */ f: number;
}

/**
 * Net flow as a rate, in [-1, 1]. Positive means a station takes in more bikes
 * than it gives out.
 *
 * Derived here rather than published, because `f` and `t` are both exact
 * integers and rounding their ratio in the artifact would round the same
 * quantity twice. It is also the form that compares across cities and across
 * station sizes: a net of +5,000 means something different at a dock with
 * 20,000 events than at one with 900,000.
 */
export function flowRate(p: StationPin): number {
  return p.t === 0 ? 0 : p.f / p.t;
}

export const stationsMeta = stationsMetaJson as {
  min_lifetime_events: number;
  omitted: {
    system_id: SystemId;
    no_coordinates: number;
    below_threshold: number;
    total: number;
  }[];
};

/** The pin list is ~260 KB and only needed once a reader reaches the maps, so
 *  it is fetched on demand rather than bundled with the page. */
let pinCache: Promise<StationPin[]> | null = null;
export function loadStations(): Promise<StationPin[]> {
  pinCache ??= import("@/data/generated/stations.json")
    .then((m) => (m.default as { stations: StationPin[] }).stations)
    // Cache the result, not the rejection. Holding a failed promise here
    // would disable all three maps for the rest of the session — every
    // remount replays the same failure with no way back.
    .catch((err) => {
      pinCache = null;
      throw err;
    });
  return pinCache;
}

/** Stations the map cannot show, so the page can say so rather than imply
 *  the network is smaller than it is. */
export function omittedFor(id: SystemId) {
  return stationsMeta.omitted.find((o) => o.system_id === id);
}

export interface FlowSystem {
  system_id: SystemId;
  /** every distinct origin-destination pair, not just the shown ones */
  pairs_total: number;
  /** trips with both ends resolvable */
  linked_trips: number;
  shown_trips: number;
  top_10: number;
  top_100: number;
  top_1000: number;
  round_trips: number;
  no_return_station: number;
  trips: number;
}

export interface FlowPair {
  /** system_id */ s: SystemId;
  /** origin station name */ a: string;
  /** destination station name */ b: string;
  /** trips */ n: number;
  /** round trip — both ends are the same dock */ r: boolean;
}

export const flows = flowsJson as {
  top_pairs_shown: number;
  systems: FlowSystem[];
  pairs: FlowPair[];
};

export function flowsFor(id: SystemId): FlowSystem | undefined {
  return flows.systems.find((f) => f.system_id === id);
}

/**
 * Share of a system's linked trips carried by its busiest `n` pairs.
 *
 * This is the cross-city comparison the flows section makes, and the reason
 * the top-pair lists beside it are labelled per-city detail: the 300 busiest
 * pairs carry 19.08% of Vancouver's linked trips and 3.35% of Montreal's, so
 * the same "top N" describes much of one network and almost none of another.
 */
export function concentration(id: SystemId, n: 10 | 100 | 1000): number | null {
  const f = flowsFor(id);
  if (!f || f.linked_trips === 0) return null;
  const carried = n === 10 ? f.top_10 : n === 100 ? f.top_100 : f.top_1000;
  return carried / f.linked_trips;
}

export interface MembershipPoint {
  system_id: SystemId;
  month: string;
  member: number;
  casual: number;
  /** neither member nor casual — Mobi's "Maintenance" pass */
  other: number;
  /** trips the source published with no membership field at all */
  unlabelled: number;
  trips: number;
}

/**
 * Membership mix.
 *
 * `series` is the comparable pair. `partial` is Montreal, which publishes
 * `is_member` for 2014-2021 and loses it at the 2022 format break — neither
 * comparable (a column ending five years early is not one) nor absent ("not
 * published" would be false for 35 million labelled trips). The registry
 * carries that third state as `partial_until`, and `make check-metrics`
 * enforces it.
 */
export const membership = membershipJson as {
  series: MembershipPoint[];
  partial: MembershipPoint[];
  partial_note: Record<string, { display?: string; partial_until?: string; reason?: string }>;
  unsupported: Record<string, { reason?: string; display?: string }>;
  /** Months the source published trips for but stopped labelling reliably.
   *  Withheld from the series, never silently dropped. */
  label_lost: {
    system_id: SystemId; month: string; member: number; casual: number;
    trips: number; basis: string;
  }[];
  /** distinct pass labels each system publishes */
  label_counts: Record<string, number>;
};

/**
 * The shape of a system's withheld window, derived rather than described.
 *
 * The gap sentence used to hardcode Toronto's figures inside a loop over every
 * system, so any other city gaining a withheld window would have rendered
 * Toronto's numbers under its own name.
 */
export function labelLostShape(id: SystemId) {
  const lost = membership.label_lost
    .filter((r) => r.system_id === id)
    .sort((a, b) => a.month.localeCompare(b.month));
  if (!lost.length) return null;
  const withLabel = lost.filter((r) => r.member > 0);
  const lastLabelled = withLabel[withLabel.length - 1];
  const firstBlank = lost.find((r) => r.member === 0);
  return {
    from: lost[0].month,
    to: lost[lost.length - 1].month,
    months: lost.length,
    trips: lost.reduce((n, r) => n + r.trips, 0),
    /** why each month was withheld — the copy must not narrate one system's
     *  failure mode under another system's name */
    bases: [...new Set(lost.map((r) => r.basis))],
    /** the busiest month the label still appeared in, and how thin it was */
    peakLabelled: withLabel.length
      ? withLabel.reduce((a, b) => (a.member > b.member ? a : b))
      : null,
    lastLabelled: lastLabelled ?? null,
    firstBlank: firstBlank ?? null,
  };
}

/** Member share of the trips that carry a label at all.
 *
 *  The denominator is member + casual, not total trips: an unlabelled trip is
 *  unknown, not casual, and folding it into the denominator would drag every
 *  share down by the labelling rate rather than by anything about riders. The
 *  unlabelled count is published alongside and stated on the page. */
export function memberShare(p: MembershipPoint): number | null {
  const labelled = p.member + p.casual;
  return labelled === 0 ? null : p.member / labelled;
}

export function membershipFor(id: SystemId): MembershipPoint[] {
  return membership.series.filter((r) => r.system_id === id);
}

/* ---------------------------------------------------------------- operations */

export interface HourPoint {
  system_id: SystemId;
  /** local hour of the event's own timestamp, 0-23 */
  hour: number;
  departures: number;
  returns: number;
}

export interface HourBasis {
  system_id: SystemId;
  linked_trips: number;
  /** distinct days with a trip, the denominator for a per-day reading */
  days: number;
  /** linked trips whose BOTH timestamps land exactly on the hour. Mobi
   *  publishes nothing finer, so Vancouver's is ~98% and the other two are
   *  effectively zero — which is why the page states the resolution. */
  on_hour_grid: number;
}

export interface RebalancingYear {
  system_id: SystemId;
  year: number;
  /** operating days: days the system had at least one linked departure */
  days: number;
  months: number;
  /** summed over days and stations, |daily net flow|. Moves are this over two,
   *  derived here rather than published so the ratio is rounded once. */
  abs_net: number;
  linked_trips: number;
  /** the archive covers this year end to end — 1 January to 31 December */
  full_year: boolean;
}

export const rebalancing = rebalancingJson as {
  hourly_first_year: number;
  hourly: HourPoint[];
  hourly_basis: HourBasis[];
  yearly: RebalancingYear[];
  /** latest calendar year the archive covers end to end for every system */
  headline_year: number | null;
  caveat: string;
  qualified: Record<string, { note?: string }>;
};

/**
 * The implied minimum number of bike moves per day.
 *
 * A LOWER BOUND, and the reason it is one travels with it everywhere: it counts
 * the imbalance a day leaves behind, assuming the network is reset overnight
 * and nothing is moved while the day runs. Any real operation moves more.
 */
export function movesPerDay(r: RebalancingYear): number {
  return r.days === 0 ? 0 : r.abs_net / 2 / r.days;
}

/** The same bound per 1,000 trips — the form that compares across systems ten
 *  times apart in size. */
export function movesPer1k(r: RebalancingYear): number {
  return r.linked_trips === 0 ? 0 : (1000 * r.abs_net) / 2 / r.linked_trips;
}

export function rebalancingFor(id: SystemId): RebalancingYear[] {
  return rebalancing.yearly.filter((r) => r.system_id === id);
}

/** The headline year's row: the latest year every system covers end to end, so
 *  all three are read over the same 365 days. */
export function headlineRebalancing(id: SystemId): RebalancingYear | undefined {
  return rebalancing.yearly.find(
    (r) => r.system_id === id && r.year === rebalancing.headline_year,
  );
}

export function hourBasis(id: SystemId): HourBasis | undefined {
  return rebalancing.hourly_basis.find((b) => b.system_id === id);
}

/** Net flow in an hour as a share of that system's linked trips in the window.
 *  Shares, not counts, for the reason the seasonality chart uses them: Montreal
 *  runs nine times Vancouver's volume and the shapes are the comparison. */
export function hourlyShare(id: SystemId): { x: number; y: number }[] {
  const basis = hourBasis(id);
  if (!basis || basis.linked_trips === 0) return [];
  return rebalancing.hourly
    .filter((r) => r.system_id === id)
    .sort((a, b) => a.hour - b.hour)
    .map((r) => ({
      x: r.hour,
      y: (100 * (r.returns - r.departures)) / basis.linked_trips,
    }));
}

/** The same hour in bikes per average operating day — the operational reading,
 *  used for the note rather than the axis. */
export function hourlyPerDay(id: SystemId, hour: number): number | null {
  const basis = hourBasis(id);
  const row = rebalancing.hourly.find((r) => r.system_id === id && r.hour === hour);
  if (!basis || !row || basis.days === 0) return null;
  return (row.returns - row.departures) / basis.days;
}

/** The hour a system's docks empty fastest, and the hour they refill fastest.
 *  Derived, because naming them in prose is how a sentence outlives its data. */
export function hourExtremes(id: SystemId): { ebb: number; flood: number } | null {
  const pts = hourlyShare(id);
  if (!pts.length) return null;
  const ebb = pts.reduce((a, b) => (b.y < a.y ? b : a));
  const flood = pts.reduce((a, b) => (b.y > a.y ? b : a));
  return { ebb: ebb.x, flood: flood.x };
}

/** Share of a system's linked trips whose timestamps are hour-only. */
export function hourGridShare(id: SystemId): number | null {
  const b = hourBasis(id);
  return b && b.linked_trips > 0 ? b.on_hour_grid / b.linked_trips : null;
}

export interface DwellRow {
  system_id: SystemId;
  /** the contiguous run of years the chain was built inside */
  era_first_year: number;
  era_last_year: number;
  year: number;
  months: number;
  /** dwell intervals: same bike, same dock, return to next departure */
  intervals: number;
  /** the bike's next departure was from a DIFFERENT dock — something moved it,
   *  so the interval is not dwell and is excluded from the quantiles */
  relocated: number;
  /** next departure recorded before the return it follows */
  out_of_order: number;
  /** intervals that are exact multiples of an hour. ~100% for Vancouver, whose
   *  source publishes no finer than the hour. */
  on_hour_grid: number;
  p25_s: number;
  median_s: number;
  p75_s: number;
}

export const dwell = dwellJson as {
  min_bike_id_coverage: number;
  series: DwellRow[];
  withheld: {
    system_id: SystemId; year: number; trips: number;
    with_bike_id: number; basis: string;
  }[];
  unsupported: Record<string, { reason?: string; display?: string }>;
  notes: Record<string, string>;
};

export function dwellFor(id: SystemId): DwellRow[] {
  return dwell.series.filter((r) => r.system_id === id);
}

/** The year ranges a system can carry dwell in, as the artifact reports them.
 *  Two for Vancouver, one for Toronto, none for Montreal. */
export function dwellEras(id: SystemId): { first: number; last: number }[] {
  const seen = new Map<string, { first: number; last: number }>();
  for (const r of dwellFor(id)) {
    seen.set(`${r.era_first_year}-${r.era_last_year}`, {
      first: r.era_first_year,
      last: r.era_last_year,
    });
  }
  return [...seen.values()].sort((a, b) => a.first - b.first);
}

export function dwellWithheldFor(id: SystemId) {
  return dwell.withheld
    .filter((r) => r.system_id === id)
    .sort((a, b) => a.year - b.year);
}

/** Share of a system's intervals that fall on an exact hour. Vancouver's
 *  quartiles are hour boundaries because its source has no finer value; the
 *  page renders this rather than asserting it. */
export function dwellGridShare(r: DwellRow): number {
  return r.intervals === 0 ? 0 : r.on_hour_grid / r.intervals;
}

/** Share of a bike's dock-to-dock intervals that ended somewhere else. Not a
 *  count of rebalancing trips: a trip missing from the archive looks the same. */
export function relocatedShare(r: DwellRow): number {
  const total = r.intervals + r.relocated;
  return total === 0 ? 0 : r.relocated / total;
}

export const incompleteMonths = incompleteJson as {
  system_id: SystemId; month: string; days_observed: number;
  days_in_month: number; trips: number;
}[];

/** Month key "2025-06" -> a sortable integer 24306, for chart x values. */
export function monthIndex(key: string): number {
  const [y, m] = key.split("-").map(Number);
  return y * 12 + (m - 1);
}

export function monthKeyFromIndex(i: number): string {
  const y = Math.floor(i / 12);
  const m = (i % 12) + 1;
  return `${y}-${String(m).padStart(2, "0")}`;
}

export function systemMeta(id: SystemId): SystemMetaRow | undefined {
  return meta.systems.find((s) => s.system_id === id);
}

/** The window every system covers, derived from the data rather than asserted. */
export function commonWindow(): { first: string; last: string } {
  const firsts = meta.systems.map((s) => s.first_trip).sort();
  const lasts = meta.systems.map((s) => s.last_trip).sort();
  return { first: firsts[firsts.length - 1], last: lasts[0] };
}
