/** Typed access to the published artifacts.
 *
 * These files are generated by pipeline/publish.py and committed. Nothing here
 * computes a statistic — if a number needs to change, it changes upstream and
 * is regenerated. The site's job is to render what the pipeline published, and
 * to state the window that came with it.
 */

import metaJson from "@/data/generated/meta.json";
import tripsMonthlyJson from "@/data/generated/trips_monthly.json";
import seasonalityJson from "@/data/generated/seasonality.json";
import stationsYearlyJson from "@/data/generated/stations_yearly.json";
import ebikeJson from "@/data/generated/ebike_share.json";
import durationJson from "@/data/generated/duration.json";
import exclusionsJson from "@/data/generated/exclusions.json";
import type { SystemId } from "@/lib/systems";

export interface SystemMetaRow {
  system_id: SystemId;
  city: string;
  system: string;
  trips: number;
  first_trip: string;
  last_trip: string;
  stations_seen: number;
  active_stations: number;
  flagged: number;
}

export interface Meta {
  generated_at: string;
  common_window_first_year: string;
  systems: SystemMetaRow[];
  window_note: string;
}

export interface MonthPoint { system_id: SystemId; month: string; trips: number }
export interface SeasonPoint { system_id: SystemId; month_of_year: number; mean_trips: number }
export interface StationPoint { system_id: SystemId; year: number; stations: number }
export interface EbikePoint {
  system_id: SystemId;
  month: string;
  ebike_trips: number;
  classified_trips: number;
}
export interface DurationRow {
  system_id: SystemId;
  median_s: number;
  p25_s: number;
  p75_s: number;
  basis_trips: number;
}
export interface ExclusionRow {
  system_id: SystemId;
  unterminated: number;
  station_matched_by_name: number;
  total: number;
}

export const meta = metaJson as Meta;
export const tripsMonthly = tripsMonthlyJson as MonthPoint[];
export const seasonality = seasonalityJson as { first_year: number; series: SeasonPoint[] };
export const stationsYearly = stationsYearlyJson as StationPoint[];
export const ebikeShare = ebikeJson as {
  series: EbikePoint[];
  unsupported: Record<string, { reason?: string; display?: string }>;
};
export const durations = durationJson as DurationRow[];
export const exclusions = exclusionsJson as ExclusionRow[];

/** Month key "2025-06" -> a sortable integer 24306, for chart x values. */
export function monthIndex(key: string): number {
  const [y, m] = key.split("-").map(Number);
  return y * 12 + (m - 1);
}

export function monthKeyFromIndex(i: number): string {
  const y = Math.floor(i / 12);
  const m = (i % 12) + 1;
  return `${y}-${String(m).padStart(2, "0")}`;
}

export function systemMeta(id: SystemId): SystemMetaRow | undefined {
  return meta.systems.find((s) => s.system_id === id);
}

/** The window every system covers, derived from the data rather than asserted. */
export function commonWindow(): { first: string; last: string } {
  const firsts = meta.systems.map((s) => s.first_trip).sort();
  const lasts = meta.systems.map((s) => s.last_trip).sort();
  return { first: firsts[firsts.length - 1], last: lasts[0] };
}
