/** Typed access to the published artifacts.
 *
 * These files are generated by pipeline/publish.py and committed. Nothing here
 * computes a statistic — if a number needs to change, it changes upstream and
 * is regenerated. The site's job is to render what the pipeline published, and
 * to state the window that came with it.
 */

import metaJson from "@/data/generated/meta.json";
import tripsMonthlyJson from "@/data/generated/trips_monthly.json";
import seasonalityJson from "@/data/generated/seasonality.json";
import stationsYearlyJson from "@/data/generated/stations_yearly.json";
import ebikeJson from "@/data/generated/ebike_share.json";
import durationJson from "@/data/generated/duration.json";
import exclusionsJson from "@/data/generated/exclusions.json";
import incompleteJson from "@/data/generated/incomplete_months.json";
import stationsMetaJson from "@/data/generated/stations_meta.json";
// Eager, unlike stations.json. At under 2 KB gzip against that file's 68 KB,
// a second lazy path would buy little and cost a failure mode — and spec 021
// demonstrated how quietly a lazy path can fail.
import flowsJson from "@/data/generated/flows.json";
import type { SystemId } from "@/lib/systems";

export interface SystemMetaRow {
  system_id: SystemId;
  city: string;
  system: string;
  trips: number;
  first_trip: string;
  last_trip: string;
  /** Distinct station IDENTITIES, not physical stations — Montreal's three
   *  unbridged key spaces inflate it. Do not render as a station count. */
  station_identities_seen: number;
  stations_note: string;
  active_stations: number;
  flagged: number;
}

export interface Meta {
  generated_at: string;
  common_window_first_year: string;
  systems: SystemMetaRow[];
  window_note: string;
}

export interface MonthPoint { system_id: SystemId; month: string; trips: number }
export interface SeasonPoint { system_id: SystemId; month_of_year: number; mean_trips: number }
export interface StationPoint { system_id: SystemId; year: number; stations: number }
export interface EbikePoint {
  system_id: SystemId;
  month: string;
  ebike_trips: number;
  classified_trips: number;
}
export interface DurationRow {
  system_id: SystemId;
  median_s: number;
  p25_s: number;
  p75_s: number;
  basis_trips: number;
}
export interface ExclusionRow {
  system_id: SystemId;
  unterminated: number;
  station_matched_by_name: number;
  total: number;
}

export const meta = metaJson as Meta;
export const tripsMonthly = tripsMonthlyJson as MonthPoint[];
export const seasonality = seasonalityJson as { first_year: number; series: SeasonPoint[] };
export const stationsYearly = stationsYearlyJson as StationPoint[];
export const ebikeShare = ebikeJson as {
  series: EbikePoint[];
  unsupported: Record<string, { reason?: string; display?: string }>;
};
export const durations = durationJson as DurationRow[];
export const exclusions = exclusionsJson as ExclusionRow[];

/** Months excluded from every series because the source has not finished
 *  publishing them (or, for van-mobi 2022-10, because the file will not
 *  download). Rendered on the site rather than buried in the runbook. */
export interface StationPin {
  /** system_id */ s: SystemId;
  /** station key */ i: string;
  /** name */ n: string;
  /** lat */ y: number;
  /** lon */ x: number;
  /** lifetime events */ t: number;
  /** currently active */ a: boolean;
  /** net flow: returns minus departures */ f: number;
}

/**
 * Net flow as a rate, in [-1, 1]. Positive means a station takes in more bikes
 * than it gives out.
 *
 * Derived here rather than published, because `f` and `t` are both exact
 * integers and rounding their ratio in the artifact would round the same
 * quantity twice. It is also the form that compares across cities and across
 * station sizes: a net of +5,000 means something different at a dock with
 * 20,000 events than at one with 900,000.
 */
export function flowRate(p: StationPin): number {
  return p.t === 0 ? 0 : p.f / p.t;
}

export const stationsMeta = stationsMetaJson as {
  min_lifetime_events: number;
  omitted: {
    system_id: SystemId;
    no_coordinates: number;
    below_threshold: number;
    total: number;
  }[];
};

/** The pin list is ~260 KB and only needed once a reader reaches the maps, so
 *  it is fetched on demand rather than bundled with the page. */
let pinCache: Promise<StationPin[]> | null = null;
export function loadStations(): Promise<StationPin[]> {
  pinCache ??= import("@/data/generated/stations.json")
    .then((m) => (m.default as { stations: StationPin[] }).stations)
    // Cache the result, not the rejection. Holding a failed promise here
    // would disable all three maps for the rest of the session — every
    // remount replays the same failure with no way back.
    .catch((err) => {
      pinCache = null;
      throw err;
    });
  return pinCache;
}

/** Stations the map cannot show, so the page can say so rather than imply
 *  the network is smaller than it is. */
export function omittedFor(id: SystemId) {
  return stationsMeta.omitted.find((o) => o.system_id === id);
}

export interface FlowSystem {
  system_id: SystemId;
  /** every distinct origin-destination pair, not just the shown ones */
  pairs_total: number;
  /** trips with both ends resolvable */
  linked_trips: number;
  shown_trips: number;
  top_10: number;
  top_100: number;
  top_1000: number;
  round_trips: number;
  no_return_station: number;
  trips: number;
}

export interface FlowPair {
  /** system_id */ s: SystemId;
  /** origin station name */ a: string;
  /** destination station name */ b: string;
  /** trips */ n: number;
  /** round trip — both ends are the same dock */ r: boolean;
}

export const flows = flowsJson as {
  top_pairs_shown: number;
  systems: FlowSystem[];
  pairs: FlowPair[];
};

export function flowsFor(id: SystemId): FlowSystem | undefined {
  return flows.systems.find((f) => f.system_id === id);
}

/**
 * Share of a system's linked trips carried by its busiest `n` pairs.
 *
 * This is the cross-city comparison the flows section makes, and the reason
 * the top-pair lists beside it are labelled per-city detail: the 300 busiest
 * pairs carry 19.08% of Vancouver's linked trips and 3.35% of Montreal's, so
 * the same "top N" describes much of one network and almost none of another.
 */
export function concentration(id: SystemId, n: 10 | 100 | 1000): number | null {
  const f = flowsFor(id);
  if (!f || f.linked_trips === 0) return null;
  const carried = n === 10 ? f.top_10 : n === 100 ? f.top_100 : f.top_1000;
  return carried / f.linked_trips;
}

export const incompleteMonths = incompleteJson as {
  system_id: SystemId; month: string; days_observed: number;
  days_in_month: number; trips: number;
}[];

/** Month key "2025-06" -> a sortable integer 24306, for chart x values. */
export function monthIndex(key: string): number {
  const [y, m] = key.split("-").map(Number);
  return y * 12 + (m - 1);
}

export function monthKeyFromIndex(i: number): string {
  const y = Math.floor(i / 12);
  const m = (i % 12) + 1;
  return `${y}-${String(m).padStart(2, "0")}`;
}

export function systemMeta(id: SystemId): SystemMetaRow | undefined {
  return meta.systems.find((s) => s.system_id === id);
}

/** The window every system covers, derived from the data rather than asserted. */
export function commonWindow(): { first: string; last: string } {
  const firsts = meta.systems.map((s) => s.first_trip).sort();
  const lasts = meta.systems.map((s) => s.last_trip).sort();
  return { first: firsts[firsts.length - 1], last: lasts[0] };
}
