"""Verify the local archive against the manifests.

Every manifest entry is classified, and the distinction that matters is
PENDING versus FAILED: a file not yet downloaded is a normal state on a
partially-acquired archive, while a file whose bytes no longer match its pin is
a reproducibility failure and must stop the pipeline.

Writes data-raw/inventory.md. Exits non-zero if anything is missing or corrupt.

Usage: python pipeline/inventory.py [--system SYSTEM] [--quiet]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import common

OK, PENDING, MISSING, CORRUPT, SIZE = "ok", "pending", "missing", "corrupt", "size"
FAILING = (MISSING, CORRUPT, SIZE)


def classify(entry: dict, path: Path) -> tuple[str, str]:
    """Return (status, detail) for one manifest entry."""
    if not entry.get("sha256"):
        return PENDING, "not downloaded yet"
    if not path.exists():
        return MISSING, f"pinned but absent: {path.name}"
    size = path.stat().st_size
    if entry.get("bytes") is not None and size != entry["bytes"]:
        return SIZE, f"{size:,}B on disk, {entry['bytes']:,}B pinned"
    actual = common.sha256_file(path)
    if actual != entry["sha256"]:
        return CORRUPT, f"sha {actual[:12]}… ≠ pinned {entry['sha256'][:12]}…"
    return OK, f"{size:,}B"


def expected_gaps(system_id: str, periods: list[str]) -> list[str]:
    """Periods the archive should contain but does not.

    Vancouver publishes monthly, so a hole in the run is a real gap. The other
    two publish annually, so only a missing year counts.
    """
    if not periods:
        return []
    if system_id == "van-mobi":
        months = sorted(p for p in periods if "-" in p)
        if not months:
            return []
        first_y, first_m = map(int, months[0].split("-"))
        last_y, last_m = map(int, months[-1].split("-"))
        want, y, m = [], first_y, first_m
        while (y, m) <= (last_y, last_m):
            want.append(f"{y}-{m:02d}")
            m += 1
            if m == 13:
                m, y = 1, y + 1
        return [p for p in want if p not in periods]
    years = sorted(int(y) for p in periods for y in [p.split("-")[0]] if y.isdigit())
    if not years:
        return []
    return [str(y) for y in range(years[0], years[-1] + 1) if not any(
        str(y) in p for p in periods)]


def check_system(system_id: str) -> tuple[dict[str, list[str]], list[str]]:
    manifest = common.load_manifest(system_id)
    sources = manifest.get("sources", {})
    buckets: dict[str, list[str]] = {}
    lines: list[str] = []

    for period in sorted(sources):
        entry = sources[period]
        path = common.local_path(system_id, period, entry.get("content_format"))
        status, detail = classify(entry, path)
        buckets.setdefault(status, []).append(period)
        lines.append(f"| `{period}` | {status} | {detail} |")

    for name, entry in (manifest.get("reference") or {}).items():
        path = common.reference_path(system_id, name)
        status, detail = classify(entry, path)
        buckets.setdefault(status, []).append(name)
        lines.append(f"| `{name}` | {status} | {detail} |")

    gaps = expected_gaps(system_id, list(sources))
    return buckets, lines + ([f"| **gaps** | missing | {', '.join(gaps)} |"] if gaps else [])


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--system", choices=sorted(common.SYSTEMS), action="append")
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args()

    systems = args.system or sorted(common.SYSTEMS)
    report = ["# Archive inventory", "",
              "Generated by `pipeline/inventory.py`. Not hand-edited.", ""]
    failures = 0

    for system_id in systems:
        meta = common.SYSTEMS[system_id]
        buckets, lines = check_system(system_id)
        failed = sum(len(buckets.get(s, [])) for s in FAILING)
        failures += failed

        summary = " · ".join(
            f"{s} {len(buckets.get(s, []))}"
            for s in (OK, PENDING, MISSING, CORRUPT, SIZE)
            if buckets.get(s)
        ) or "no entries"
        header = f"## {meta['city']} — {meta['system']} (`{system_id}`)"
        report += [header, "", summary, "", "| entry | status | detail |",
                   "| --- | --- | --- |"] + lines + [""]
        if not args.quiet:
            print(f"{system_id}: {summary}")
            for status in FAILING:
                for period in buckets.get(status, []):
                    print(f"  {status.upper()}: {period}", file=sys.stderr)

    out = common.DATA_RAW / "inventory.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(report) + "\n", encoding="utf-8")
    if not args.quiet:
        print(f"\nwrote {out}")
    if failures:
        print(f"{failures} entr(ies) missing or corrupt", file=sys.stderr)
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
