"""Regenerate docs/data-quality-report.md from the warehouse.

Every row this pipeline drops or flags is accounted for here. The report is
generated, committed, and never hand-edited — if a number in it is wrong, the
fix is upstream, not in the prose.

Usage: python pipeline/quality_report.py [--db PATH] [--out PATH]
"""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
from pathlib import Path

import duckdb

import common

OUT = common.REPO_ROOT / "docs" / "data-quality-report.md"


def table(headers: list[str], rows: list[tuple], align: str | None = None) -> list[str]:
    sep = align or "| " + " | ".join("---" for _ in headers) + " |"
    out = ["| " + " | ".join(headers) + " |", sep]
    for r in rows:
        out.append("| " + " | ".join("" if c is None else str(c) for c in r) + " |")
    return out + [""]


def fmt(n) -> str:
    return f"{n:,}" if isinstance(n, (int, float)) and n is not None else str(n)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--db", type=Path, default=common.DATA_WAREHOUSE / "bikeshare.duckdb")
    ap.add_argument("--out", type=Path, default=OUT)
    args = ap.parse_args()

    con = duckdb.connect(str(args.db), read_only=True)
    q = lambda sql, p=None: con.execute(sql, p or []).fetchall()

    doc = [
        "# Data Quality Report",
        "",
        "Generated by `pipeline/quality_report.py` from the warehouse. Not "
        "hand-edited — if a figure here is wrong, the fix is upstream.",
        "",
        f"Generated {datetime.now(timezone.utc).isoformat(timespec='seconds')}.",
        "",
        "## Row funnel",
        "",
        "Every row that entered the pipeline is either kept or dropped for a "
        "named reason. The two must sum to what landed.",
        "",
    ]

    metrics = dict(((s, m), v) for s, m, v in
                   q("SELECT stage, metric, value FROM etl_metrics"))
    landed = metrics.get(("extract", "rows_landed"), 0)
    kept = metrics.get(("clean", "rows_kept"), 0)
    named = [
        ("no parseable departure time", metrics.get(("clean", "rows_dropped_no_departure_time"), 0)),
        ("no departure station", metrics.get(("clean", "rows_dropped_no_departure_station"), 0)),
        ("exact duplicate", metrics.get(("clean", "rows_dropped_duplicates"), 0)),
    ]
    doc += table(
        ["stage", "rows", "share"],
        [("landed", fmt(landed), "100.000%")]
        + [(f"dropped — {label}", fmt(n), f"{100 * n / landed:.3f}%" if landed else "—")
           for label, n in named]
        + [("**kept**", f"**{fmt(kept)}**",
            f"**{100 * kept / landed:.3f}%**" if landed else "—")],
    )
    residual = landed - kept - sum(n for _, n in named)
    doc += [
        f"Funnel residual: **{residual:,}** — this must be zero. It is derived, "
        "not asserted: the duplicate count is computed as landed minus kept "
        "minus the other named reasons, so a non-zero residual would mean a "
        "reason is double-counted.",
        "",
        "## Per system",
        "",
    ]

    doc += table(
        ["system", "trips", "first", "last", "stations", "active", "flagged"],
        [(f"{common.SYSTEMS[s]['city']} — {common.SYSTEMS[s]['system']}",
          fmt(n), str(a), str(b), fmt(st), fmt(act), f"{fmt(fl)} ({100*fl/n:.2f}%)")
         for s, n, a, b, st, act, fl in q("""
            SELECT f.system_id, count(*), min(f.departure_ts)::DATE, max(f.departure_ts)::DATE,
                   count(DISTINCT f.departure_station_id),
                   (SELECT count(*) FROM dim_station d
                     WHERE d.system_id = f.system_id AND d.is_active),
                   sum(CASE WHEN f.has_quality_issue THEN 1 ELSE 0 END)
            FROM fact_trips f GROUP BY 1 ORDER BY 1""")],
    )

    doc += ["## Quality flags", "",
            "Flags mark; they never delete. A flagged trip is still a trip.", ""]
    flags = q("""
      SELECT system_id, flag, count(*) AS n
      FROM (SELECT system_id, unnest(quality_flags) AS flag FROM fact_trips)
      GROUP BY 1, 2 ORDER BY 1, 3 DESC
    """)
    totals = dict(q("SELECT system_id, count(*) FROM fact_trips GROUP BY 1"))
    doc += table(["system", "flag", "trips", "share of system"],
                 [(s, f, fmt(n), f"{100 * n / totals[s]:.2f}%") for s, f, n in flags])

    doc += ["## Station identity", "",
            "A station resolved by name is a weaker claim than one resolved by "
            "a published id. This is how much of each system rests on name "
            "matching.", ""]
    doc += table(
        ["system", "trips by id", "trips by name", "name share"],
        [(s, fmt(t - n), fmt(n), f"{100 * n / t:.2f}%") for s, t, n in q("""
           SELECT system_id, count(*),
                  count(*) FILTER (list_contains(quality_flags, 'station_matched_by_name'))
           FROM fact_trips GROUP BY 1 ORDER BY 1""")],
    )

    doc += ["## Membership labels", "",
            "Raw labels are mapped explicitly. An unmapped label is reported "
            "here rather than silently bucketed.", ""]
    doc += table(["system", "raw label", "group", "trips"],
                 [(s, r, g if g else "**UNMAPPED**", fmt(n)) for s, r, g, n in q("""
                    SELECT f.system_id, f.membership_raw, m.membership_group, count(*)
                    FROM fact_trips f
                    LEFT JOIN dim_membership m
                      ON m.system_id = f.system_id AND m.membership_raw = f.membership_raw
                    WHERE f.membership_raw IS NOT NULL
                    GROUP BY 1, 2, 3 ORDER BY 1, 4 DESC""")])

    doc += ["## Trips per month", "", "<details><summary>Full series</summary>", ""]
    doc += table(["system", "month", "trips"],
                 [(s, m, fmt(n)) for s, m, n in q("""
                    SELECT system_id, strftime(trip_month, '%Y-%m'), count(*)
                    FROM fact_trips GROUP BY 1, 2 ORDER BY 1, 2""")])
    doc += ["</details>", ""]

    con.close()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(doc), encoding="utf-8")
    print(f"wrote {args.out}")
    print(f"funnel residual: {residual:,}")
    return 1 if residual != 0 else 0


if __name__ == "__main__":
    raise SystemExit(main())
