import { existsSync, readFileSync } from "node:fs";
import nodePath from "node:path";
import { describe, expect, it } from "vitest";

/**
 * The social card: the declaration in `index.html`, and the file it declares.
 *
 * `og:image` is the one asset on this site whose failure is invisible from the
 * site itself — a missing or wrongly-sized PNG looks perfect in a browser and
 * broken in every place the link is shared. So the file is checked here rather
 * than trusted: present, a real PNG, and exactly the 1200x630 the meta claims.
 *
 * It is generated by rendering `public/og-image.html` in a headed browser; the
 * command and the provenance are in `public/og-image-PROVENANCE.md`. Until that
 * render has been done, the dimension test below FAILS — deliberately. A
 * placeholder that made the suite green would be the site asserting a card it
 * does not have.
 */

// Vitest runs with the project root as its working directory.
const path = (p: string) => nodePath.resolve(process.cwd(), p);
const html = readFileSync(path("index.html"), "utf8");

const PNG = path("public/og-image.png");
const URL_BASE = "https://bikeshare.adnanreza.com";

function meta(attr: "property" | "name", key: string): string | null {
  const re = new RegExp(`<meta[^>]*\\b${attr}="${key}"[^>]*>`, "i");
  const tag = re.exec(html)?.[0];
  return tag ? (/content="([^"]*)"/i.exec(tag)?.[1] ?? null) : null;
}

/** Width and height from the IHDR chunk — bytes 16-23 of a PNG. */
function pngSize(file: string): { width: number; height: number } {
  const buf = readFileSync(file);
  const signature = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
  expect(buf.subarray(0, 8).equals(signature), `${file} is not a PNG`).toBe(true);
  expect(buf.subarray(12, 16).toString("ascii")).toBe("IHDR");
  return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20) };
}

describe("social card metadata", () => {
  it("declares an absolute og:image with its dimensions and alt text", () => {
    expect(meta("property", "og:image")).toBe(`${URL_BASE}/og-image.png`);
    expect(meta("property", "og:image:width")).toBe("1200");
    expect(meta("property", "og:image:height")).toBe("630");
    expect((meta("property", "og:image:alt") ?? "").length).toBeGreaterThan(20);
  });

  it("declares a large Twitter card pointing at the same image", () => {
    expect(meta("name", "twitter:card")).toBe("summary_large_image");
    expect(meta("name", "twitter:title")).toBe("Trans-Canada Bikeshare");
    expect((meta("name", "twitter:description") ?? "").length).toBeGreaterThan(20);
    expect(meta("name", "twitter:image")).toBe(meta("property", "og:image"));
  });

  it("keeps the composition self-contained: no external fetch at render time", () => {
    const card = readFileSync(path("public/og-image.html"), "utf8");
    expect(card).toContain("1200px");
    expect(card).toContain("630px");
    // Nothing off-machine. A card that needed the network would render
    // differently depending on when and where it was screenshotted.
    expect(card).not.toMatch(/(src|href)="https?:/);
    expect(card).toContain("data:font/woff2;base64,");
  });
});

describe("public/og-image.png", () => {
  it("exists — run scripts/make-og-image.mjs, then render it headed to PNG", () => {
    expect(
      existsSync(PNG),
      "public/og-image.png is missing. index.html promises it at 1200x630; " +
        "render public/og-image.html in a headed browser and save it there. " +
        "See public/og-image-PROVENANCE.md.",
    ).toBe(true);
  });

  it("is exactly the 1200x630 index.html declares", () => {
    expect(existsSync(PNG), "public/og-image.png is missing").toBe(true);
    expect(pngSize(PNG)).toEqual({ width: 1200, height: 630 });
  });
});
